language: java

jdk:
  - oraclejdk8
  - oraclejdk7

branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+/

env:
  global:
    - secure: S41a70+hDxvP1EJUFRxd36M5LpzmSMf5VTUlwqlAdgxL1q+KnKGRuSww5YaNV4g8QUUsIMTEpvXi/mRXuh4pDJHX5I+457skkT1mYGl/MJsThVeI5uYJSf8yfy9QquPDUsxIJiEJ0K2A5R+c1b2V3edtljrk+lpcgXH0St/wvJIHnMQEO1L6YII36ujwLgiDMYDn2dlTetGBUg9Ya+jxAEeVi/wmGV69/aF2heWsNOhXUFrbPH8MXzpxAtgPlsymLpVhxbf84SRkFyHoGevavTYV6l0ZmFBXKE6JMRtBxqKCn2viXtPknue1/S8ydNqxVfSgv+91UaO8yqwIQq0D1wfUyUk1Gj/Q1/kfXODCGNIHdwCCzTUd/BBHpbYBAZOk6w6wAucAoux/hHjIb46YTJjLhQtWtemD47wvae/S3B1YaCTwytPmgw1RFKgUkGZyywOTdREkM55elfr2s8m9Ge4L2/WtmFuefKj0NsuviJmgr3L02BNOOhILBPcbIXg8Nb8ooV8+1a6QHcepakCNIRIjSnQwZfffAf9IdtcF2bLhhzeSbW1Ama+Obnthz6UaI0/gKKVPCazV0i9NJashIc4v7v4dl5HjNNgLRFS17fJqpJvV6NWtmeC2aPgj5GUUvbwc5Y1SngT4lVKMw2ZLfNh2nWfXk5mJd2+B1MhcOAQ=
    - secure: a5oKqyg2dxkyMkaQ80XFrm0Wsq481co/nIjomKBSH6fSyigq/OL+wq5BCe5cXt7wswLvMXWqTwnKMXBRdRKpYvfyMig/6sYelcCD6pxOb5vwprCARcvcWHjRmdkL4RaY8cvRwFL0dGDt09FpIg0JjNtlFUHF5vYK6UJaK1d5VT3oRVb6uos6YwkXSUcqdrM3sx99d95h2W5vBJXs1sspw3LLqrCX+x5NLna/Tk+MI/EN9ua+jdbrVnWwsqZofQo4lz2zu3eoPsjw1TqgUyRSVdb1fhqRiD0XO047uqXHycwGVwipd7VydwE3w9MpVAljTXSw7TRLAtmbFp/3BQefynqiETMOZQ3lndeUVBKFEU5Mv8t0Vjzz2HkpAjYk4RYdUeeJFLdDBU/mPvQXv+7IlKbF133CnsZPkSd1GlKIYfgsQGElKAGdACFe2XhJ8cmqQjVkxlqsShQZXiULLYb4HJA3K1cvIpD7WbMZgQp5uVviKQSUhq3nOr4fvDiArF/DpQYWsKTEAm8KCzn0iiy4scpr5xP1dVJxyfNIXO9YQnys4KnYU1hBTt3wiRaQNDwl191TOGDTrO17rkwte3s9aDY7157+a8mxiKHYORTqIJ9zo6NqkcnsdqUhqyF9OGYzLO7Bl5p6UUe6/zj0r9+QoEpls1d2WcnGzMEDjT6tiwI=

after_success:
  - test "${TRAVIS_JDK_VERSION}" == "oraclejdk7" && ./gradlew jacocoTestReport coveralls
  - test "${TRAVIS_TAG}" != "" && test "${TRAVIS_JDK_VERSION}" == "oraclejdk7" && ./gradlew bintrayUpload